[package]
name = "http-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.2"
chrono = "0.4.31"
clap = { version = "4.5.31", features = ["derive"] }
